#!/bin/bash

# Removes the firefox-gnome-theme.

# All firefox installation paths.
firefoxInstallationPaths=(
    $HOME/.mozilla/firefox
    $HOME/.var/app/org.mozilla.firefox/.mozilla/firefox
    $HOME/.librewolf
    $HOME/.var/app/io.gitlab.librewolf-community/.librewolf
    $HOME/snap/firefox/common/.mozilla/firefox
)

foldersFoundCount=0

# For every installation path..
for folder in "${firefoxInstallationPaths[@]}"; do
    # ..if the path exists..
    if [ -d "$folder" ]; then
		echo -e "Firefox installation folder found in:\n$folder"
		foldersFoundCount+=1

		# Delete old theming.
		find "$folder" -mindepth 2 -maxdepth 2 -type l -name 'user.js' -delete
		find "$folder" -mindepth 2 -maxdepth 2 -type d -name 'chrome' -exec rm -rf {} +
        echo "Theme removed."
    fi
done

# If no installation path exists.
if [ $foldersFoundCount = 0 ];then
    echo No firefox folder found.
fi