#!/bin/bash

# Downloads thunderbird-gnome-theme from GitHub & uses custom accent if it's set.
# Deletes previously installed theme, so it can be used for upgrades.

# Setup variables
WORKDIR="/tmp/thunderbird-gnome-theme"
ACCENT_COLOR=$(awk '/@define-color accent_color/{ print substr( $3, 1, length($3)-1 ) }' $HOME/.config/gtk-4.0/gtk.css 2> /dev/null)
ACCENT_BG_COLOR=$(awk '/@define-color accent_bg_color/{ print substr( $3, 1, length($3)-1 ) }' $HOME/.config/gtk-4.0/gtk.css 2> /dev/null)

# Color codes
TITLE_CLR='\e[1m'
RESET='\e[0m'

echo -e "${TITLE_CLR}Installing thunderbird-gnome-theme with a custom accent..${RESET}\n"

# Cleanup WORKDIR just in case.
rm -rf "$WORKDIR"

# Clone the theme.
git clone "https://github.com/rafaelmardojai/thunderbird-gnome-theme.git" "$WORKDIR"

# Set custom accent color if it's set in gtk.css.
if [ -n "$ACCENT_COLOR" ] && [ -n "$ACCENT_BG_COLOR" ]; then
	# LIGHT theme override.
	sed -i "s|--gnome-accent-bg:.*|--gnome-accent-bg: $ACCENT_BG_COLOR;|" "$WORKDIR/theme/colors/light.css"
	sed -i "s|--gnome-accent:.*|--gnome-accent: $ACCENT_COLOR;|" "$WORKDIR/theme/colors/light.css"

	# DARK theme override.
	sed -i "s|--gnome-accent-bg:.*|--gnome-accent-bg: $ACCENT_BG_COLOR;|" "$WORKDIR/theme/colors/dark.css"
	sed -i "s|--gnome-accent:.*|--gnome-accent: $ACCENT_COLOR;|" "$WORKDIR/theme/colors/dark.css"
fi

# Install.

# All thunderbird installation paths.
thunderbirdInstallationPaths=(
    ~/.thunderbird
    ~/.var/app/org.mozilla.Thunderbird/.thunderbird
    ~/snap/thunderbird/common/.thunderbird
    ~/.var/app/eu.betterbird.Betterbird/.thunderbird
)

foldersFoundCount=0

# For every installation path..
for folder in "${thunderbirdInstallationPaths[@]}"; do
	# ..if the path exists..
    if [ -d "$folder" ]; then
		echo Thunderbird installation folder found.
		foldersFoundCount+=1

		# Delete old theming.
		find "$folder" -mindepth 2 -maxdepth 2 -type l -name 'user.js' -delete
		find "$folder" -mindepth 2 -maxdepth 2 -type d -name 'chrome' -exec rm -rf {} +

		# Install the theme.
		eval "$WORKDIR/scripts/install.sh" -f "$folder"
    fi
done

# If no installation path exists.
if [ $foldersFoundCount = 0 ]; then
    echo No Thunderbird folder found.
fi

# Cleanup.
rm -rf "$WORKDIR"
