#!/bin/bash

# Sets rounded corners for a horizontal Dash-to-Panel layout.
# Not a solution, a hack for https://github.com/home-sweet-gnome/dash-to-panel/issues/1819
# Possible, thanks to https://github.com/home-sweet-gnome/dash-to-panel/issues/1721

# Local installation is preferred, but system-wide will work too if the script runs with sudo.
# Detects GNOME shell version and acts accordingly. (Extension was rewritten for GNOME 45+)
# Detects and warns immutable distro users trying to install system-wide.
# Detects Zorin OS and acts accordingly. (They rename some values)
# You can alter the 'SETUP VARIABLES' as you like, you shouldn't touch the rest.

# ------------------- SETUP VARIABLES --------------------------------------------------#
ADD_PANEL_HEIGHT=8 # Should be exactly twice of BORDERS
BORDERS=4
BORDER_RADIUS=10
# ------------------- SETUP VARIABLES --------------------------------------------------#

# Color codes
BOLD_CLR='\033[1m'
SUCCESS_CLR='\e[32m'
FAIL_CLR='\e[31m'
RESET_CLR='\e[0m'

echo -e "${BOLD_CLR}Setting up custom Dash-to-Panel${RESET_CLR}"

# Check if OS matches Zorin..
if cat /etc/os-release | grep -wq 'Zorin OS'; then
	#.. it does.
	EXTENSION="zorin-taskbar@zorinos.com"
	echo -e "  ▪ Zorin OS ${SUCCESS_CLR}detected${RESET_CLR}."
else
	#.. it does NOT.
	EXTENSION="dash-to-panel@jderose9.github.com"
fi

EXTENSION_PATH_LOCAL="${HOME}/.local/share/gnome-shell/extensions/${EXTENSION}"
EXTENSION_PATH_SYSTEM="/usr/share/gnome-shell/extensions/${EXTENSION}"

# Check if it's installed..
if [ -d "${EXTENSION_PATH_LOCAL}" ]; then
	#.. yes, locally.
	EXTENSION_PATH="${EXTENSION_PATH_LOCAL}"
	echo -e "  ▪ Local installation ${SUCCESS_CLR}found${RESET_CLR}."
elif [ -d "${EXTENSION_PATH_SYSTEM}" ]; then
	#.. yes, system-wide.
	EXTENSION_PATH="${EXTENSION_PATH_SYSTEM}"
	echo -e "  ▪ System-wide installation ${SUCCESS_CLR}found${RESET_CLR}."
	
	# Check for root privileges..
	if [ "${EUID}" -ne 0 ]; then
		#.. we DON'T have them.
		echo -e "    ▪ Need ${FAIL_CLR}higher privileges${RESET_CLR} to proceed."
		echo "      ▪ Please run the script again with sudo."
		exit 1
	else
		#.. we have them, check for immutable distros..
		if touch "${EXTENSION_PATH}/ro_test" 2> /dev/null; then
			# .. running classic distro.
			rm -f "${EXTENSION_PATH}/ro_test"
		else
			#.. running immutable.
			echo -e "    ▪ Detected an ${FAIL_CLR}immutable distribution${RESET_CLR}."
			echo "      ▪ Please install the extension locally and run the script without sudo."
			exit 1
		fi
	fi
else
	#.. not installed.
    echo -e "  ▪ The extension is ${FAIL_CLR}not installed${RESET_CLR}."
    exit 1
fi

echo "    ▪ Installing to: '${EXTENSION_PATH}'"

# Alter panel.js

SHELL_VERSION=$(gnome-shell --version | cut -d' ' -f3 | cut -d'.' -f1)

# Check GNOME shell version..
if [ ${SHELL_VERSION} -lt 45 ]; then
	#.. older versions 
	SETTINGS_VAR="Me.settings"
else
	#.. version 45+
	SETTINGS_VAR="SETTINGS"
fi

sed -i "s|const panelSize.*|const panelSize = PanelSettings.getPanelSize(${SETTINGS_VAR}, this.monitor.index) + ${ADD_PANEL_HEIGHT};|" "${EXTENSION_PATH}/panel.js"

# Prepare stylesheet.css addition

CLASSNAME_VAR=$(cut -d'@' -f1 <<< ${EXTENSION} | sed 's|-||g')

ADD_STYLESHEET=\
"/*Customized, issue 1819*/
#${CLASSNAME_VAR}Scrollview .app-well-app:hover .dtp-container,
#${CLASSNAME_VAR}Scrollview .app-well-app:focus .dtp-container,
#${CLASSNAME_VAR}Scrollview .app-well-app .dtp-container > StWidget {
  border-radius: ${BORDER_RADIUS}px;
}
#${CLASSNAME_VAR}Scrollview .dash-item-container > StWidget { 
  border-top: ${BORDERS}px;
  border-bottom: ${BORDERS}px;
}
/*Customized, issue 1819*/"

# Alter stylesheet.css

# Check if we added customizations to stylesheet.css before..
if ! grep -qF "/*Customized, issue 1819*/" "${EXTENSION_PATH}/stylesheet.css"; then
    #.. no, add them.
    echo -e "\n${ADD_STYLESHEET}" >> "${EXTENSION_PATH}/stylesheet.css"
else
    #.. yes, replace them.
    awk -i inplace -v ADD_STYLESHEET="${ADD_STYLESHEET}" '/\/\*Customized, issue 1819\*\// {
        if (!inside_block) {
            print ADD_STYLESHEET;
            inside_block = 1;
            next;
        } else {
            inside_block = 0;
            next;
        }
    } !inside_block' "${EXTENSION_PATH}/stylesheet.css"
fi

echo -e "      ▪ ${SUCCESS_CLR}Done${RESET_CLR}. You'll need to log-out, log-in to see the changes for some reason."