#!/bin/bash

# Clones gnome-shell from GitLab & compiles the theme with a custom accent.
#
# !!! Works for GNOME 45 and up !!!

# Setup variables
THEME_NAME_LIGHT="gnome-shell-custom-light"
THEME_NAME_DARK="gnome-shell-custom-dark"
ACCENT_FILE="${HOME}/.config/gtk-4.0/gtk.css"
ACCENT_COLOR_LIGHT=$(awk '/@define-color accent_bg_color/{ print substr( $3, 1, length($3)-1 ) }' "${ACCENT_FILE}" 2> /dev/null)
ACCENT_COLOR_DARK=$(awk '/@define-color accent_color/{ print substr( $3, 1, length($3)-1 ) }' "${ACCENT_FILE}" 2> /dev/null)
THEME_PATH="${HOME}/.local/share/themes"
SHELL_VERSION="$(gnome-shell --version | awk '{print $3}')"
WORKDIR="/tmp/gnome-shell"

# Color codes
TITLE_CLR='\e[1m'
RESET='\e[0m'

echo -e "${TITLE_CLR}Creating a gnome-shell theme with a custom accent..${RESET}\n"

# Do we have accent color ?
if [ -z "${ACCENT_COLOR_DARK}" ]; then
	echo "Accent color in '${ACCENT_FILE}' is missing. Set a custom accent color first."
	exit 1
fi

# Do we have sassc ?
if ! type sassc &> /dev/null; then
	echo "Missing 'sassc'. Install it using your package manager."
	exit 1
fi

# Cleanup WORKDIR just in case.
rm -rf "${WORKDIR}"

# Clone gnome-shell repo to '/tmp'.
git clone --branch ${SHELL_VERSION} "https://gitlab.gnome.org/GNOME/gnome-shell.git" "${WORKDIR}" &> /dev/null
if [ $? -eq 128 ]; then
	while [ True ]; do
		echo -e " ─ Version ${SHELL_VERSION} doesn't exist."
		read -p "     └─ Set a custom version: " SHELL_VERSION
		git clone --branch ${SHELL_VERSION} "https://gitlab.gnome.org/GNOME/gnome-shell.git" "${WORKDIR}" &> /dev/null
		if [ $? -eq 0 ]; then
			break
		fi
	done
fi

# ---- DARK ---- #

# Set a custom accent color.
sed -i "s|\$blue_3.*|\$blue_3: ${ACCENT_COLOR_DARK};|" "${WORKDIR}/data/theme/gnome-shell-sass/_palette.scss"

# Compile the theme.
sassc -a "${WORKDIR}/data/theme/gnome-shell-dark.scss" "${WORKDIR}/data/theme/gnome-shell-dark.css"

# Remove previously created theme and copy the new one.
rm -rf "${THEME_PATH}/${THEME_NAME_DARK}"
mkdir -p "${THEME_PATH}/${THEME_NAME_DARK}/gnome-shell"
cp "${WORKDIR}/data/theme/gnome-shell-dark.css" "${THEME_PATH}/${THEME_NAME_DARK}/gnome-shell/gnome-shell.css"

# ---- LIGHT ---- #

if [ -n "${ACCENT_COLOR_LIGHT}" ]; then
	# Set a custom accent color.
	sed -i "s|\$blue_3.*|\$blue_3: ${ACCENT_COLOR_LIGHT};|" "${WORKDIR}/data/theme/gnome-shell-sass/_palette.scss"

	# Compile the theme.
	sassc -a "${WORKDIR}/data/theme/gnome-shell-light.scss" "${WORKDIR}/data/theme/gnome-shell-light.css"

	# Remove previously created theme and copy the new one.
	rm -rf "${THEME_PATH}/${THEME_NAME_LIGHT}"
	mkdir -p "${THEME_PATH}/${THEME_NAME_LIGHT}/gnome-shell"
	cp "${WORKDIR}/data/theme/gnome-shell-light.css" "${THEME_PATH}/${THEME_NAME_LIGHT}/gnome-shell/gnome-shell.css"
fi

# Cleanup.
rm -rf "${WORKDIR}"

echo -e "\nDone. Set the user theme in gnome-tweaks."