#!/bin/bash

# Allows Flatpak to access folders related to theming.

override_flatpak_perms () {
    if [ "$1" == "--system" ]; then
        PREFIX="pkexec "
    fi

    ${PREFIX}flatpak "$1" override \
    --filesystem="xdg-config/gtk-3.0:ro" \
    --filesystem="xdg-config/gtk-4.0:ro" \
    --filesystem="xdg-data/icons:ro" \
    --filesystem="xdg-data/themes:ro"
}

override_flatpak_perms --user
override_flatpak_perms --system