#!/bin/bash

# Allows Flatpak to access folders related to theming.

sudo flatpak override \
--filesystem="xdg-config/gtk-3.0:ro" \
--filesystem="xdg-config/gtk-4.0:ro" \
--filesystem="xdg-data/icons:ro" \
--filesystem="xdg-data/themes:ro"
