#!/bin/bash

# Downloads Adwaita-for-Steam theme from GitHub & uses custom accent if it's set.

# ----------------- GIT UPDATER ------------------------------------------------------------------ #

URL="https://github.com/tkashkin/Adwaita-for-Steam"

# ------------------------------------------------------------------------------------------------ #
NAME="$(awk -F/ '{sub(/\.git$/, "", $5); print $5}' <<< "${URL}")"
WORKDIR="/tmp/${NAME}"
UPDATER="${HOME}/.local/share/git-updater/git-updater"

# Cleanup WORKDIR just in case.
rm -rf "$WORKDIR"

# Download the theme OR check for updates.
if [ "$1" == "--update-mode" ]; then
	# Do we have git-updater ?
	if ! type ${UPDATER} &> /dev/null; then
		echo "Cannot check for updates as git-updater doesn't exist in the git-updater folder."
		exit 1
	fi
	# We have it, run it.
	bash ${UPDATER} ${URL}
	# All up to date, exit.
	if [ $? -eq 123 ]; then
		exit 0
	fi
	# Completely suppress the output
	exec &> /dev/null
else
	# Normal mode, clone the theme.
	echo -e "\e[1mInstalling ${NAME} with a custom accent..\e[0m\n"
	git clone ${URL} "${WORKDIR}"
fi
# ------------------------------------------------------------------------------------------------ #

# Inverted colors, is intended. (Looks better)
ACCENT_COLOR=$(awk '/@define-color accent_bg_color/{ print substr( $3, 1, length($3)-1 ) }' $HOME/.config/gtk-4.0/gtk.css 2> /dev/null)
ACCENT_BG_COLOR=$(awk '/@define-color accent_color/{ print substr( $3, 1, length($3)-1 ) }' $HOME/.config/gtk-4.0/gtk.css 2> /dev/null)

# Set custom accent color if it's set in gtk.css.
if [ -n "${ACCENT_COLOR}" ] && [ -n "${ACCENT_BG_COLOR}" ]; then
cat << EOF > "${WORKDIR}/custom/custom.css"
:root
{
    --accent: ${ACCENT_COLOR};
    --accent_bg: ${ACCENT_BG_COLOR};
    --accent_disabled: ${ACCENT_COLOR}80;
    --accent_hover_bg: ${ACCENT_BG_COLOR}12;
    --accent_active_bg: ${ACCENT_BG_COLOR}29;
    --focusring: ${ACCENT_COLOR}80;
}
EOF
fi

# Install.
cd "${WORKDIR}"
./install.py --custom-css --extra windowcontrols/right-all

# Cleanup.
rm -rf "${WORKDIR}"
