#!/bin/bash

# Mirrors current monitor settings for GDM (GNOME's login screen)

echo 'Mirroring current monitor settings to GDM.'

if [ -s ~/.config/monitors.xml ]; then
	sudo install -o gdm -g gdm -m 644 ~/.config/monitors.xml ~gdm/.config/
else
	echo "Missing monitor configuration."
	exit 1
fi
